### ISSUE TITLE
支持 hessian 4

### ISSUE THREAD

**Issue by gxcsoccer** [alipay/sofa-hessian-node#3]
## 背景

因为蚂蚁内部一直用的是 hessian 3，而且 3 和 4 不兼容，所以现在开源的版本只支持 3。但是在阿里集团和外部很多人使用的是 4，所以要予以支持

相关 [issue](https://github.com/alipay/sofa-rpc/issues/217)

**Comment by HuangSheng** [comment]
好像现在的这个sofa-hessian-node版本不支持hessian4，是否可以考虑node版也支持hessian4？
